kind: Service
apiVersion: v1
metadata:
  name: articles-ms
  labels:
    app: articles-ms
spec:
  selector:
    app: articles-ms
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-ms

  labels:
    app: articles-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles-ms
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: articles-ms
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "articles-ms"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "8080"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: articles-ms
        image: ttl.sh/articles-ms-java:5h
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: orders-ms
  labels:
    app: orders-ms
spec:
  selector:
    app: orders-ms
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-ms

  labels:
    app: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: orders-ms
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orders-ms"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "8081"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: orders-ms
        image: ttl.sh/orders-ms-golang:5h
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: payment-ms
  labels:
    app: payment-ms
spec:
  selector:
    app: payment-ms
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms

  labels:
    app: payment-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: payment-ms
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "payment-ms"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "5000"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: payment-ms
        image: ttl.sh/payment-ms-python:5h
        imagePullPolicy: Always