kind: Service
apiVersion: v1
metadata:
  name: orders-ms
  labels:
    app: orders-ms
spec:
  selector:
    app: orders-ms
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-ms

  labels:
    app: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: orders-ms
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orders-ms"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "8081"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: orders-ms
        image: ttl.sh/orders-ms-golang:5h
        imagePullPolicy: Always
