apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-pubsub
spec:
  type: pubsub.azure.servicebus.queues
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: servicebus-connection-string
auth:
  secretStore: secretstore