apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.aws.parameterstore
  version: v1
  metadata:
  - name: accessKey
    secretKeyRef:
      name: aws-creds
      key:  accessKey
  - name: secretKey
    secretKeyRef:
      name: aws-creds
      key:  secretKey
  - name: region
    value: "eu-west-1"



