apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub  
  namespace: default      
spec:
  type: pubsub.rabbitmq    
  version: v1
  metadata:
  - name: host             
    value: amqp://rabbitmq.default.svc.cluster.local:5672  
  - name: consumerID
    value: order
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: 0.5
  - name: prefetchCount
    value: 10
  - name: maxLen
    value: 10000
  - name: maxPriority
    value: 10
  - name: auth.password    
    secretKeyRef:
      name: rabbitmq-secret
      key: password
  - name: auth.username    
    secretKeyRef:
      name: rabbitmq-secret
      key: username
  - name: enableTLS        
    value: "false"
auth:
  secretStore: kubernetes  
