apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "${workload_identity}"
    azure.workload.identity/use: "true"
  name: "workload-identity-sa"
  namespace: "default"